version: "3.9"
services:
  tg:
    build: .
    ports:
      - "8001:8000"
    container_name: tg_stas
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: on-failure
    volumes:
      - ./.:/app
